# Generated by Django 4.2.1 on 2023-05-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
